import type { Recipe } from "@/types/recipe";

export const sampleRecipes: Recipe[] = [
	{
		id: "1",
		name: "Grilled Salmon with Asparagus",
		description:
			"A healthy and delicious salmon dish packed with omega-3 fatty acids and fresh vegetables.",
		image: "https://picsum.photos/400/300?random=1",
		category: "Dinner",
		cuisine: "American",
		prepTime: 10,
		cookTime: 15,
		servings: 2,
		difficulty: "Easy",
		calories: 420,
		nutrition: {
			protein: 35,
			carbs: 8,
			fat: 28,
			fiber: 4,
			sugar: 3,
		},
		ingredients: [
			{
				id: "1",
				name: "Salmon fillet",
				amount: 8,
				unit: "oz",
				notes: "skin-on",
			},
			{
				id: "2",
				name: "Asparagus",
				amount: 1,
				unit: "bunch",
				notes: "trimmed",
			},
			{ id: "3", name: "Olive oil", amount: 2, unit: "tbsp" },
			{
				id: "4",
				name: "Lemon",
				amount: 1,
				unit: "whole",
				notes: "juiced and zested",
			},
			{ id: "5", name: "Garlic", amount: 2, unit: "cloves", notes: "minced" },
			{ id: "6", name: "Salt", amount: 1, unit: "tsp" },
			{
				id: "7",
				name: "Black pepper",
				amount: 0.5,
				unit: "tsp",
				notes: "freshly ground",
			},
		],
		instructions: [
			"Preheat grill to medium-high heat (about 400°F).",
			"Pat salmon dry and season both sides with salt and pepper.",
			"In a small bowl, whisk together olive oil, lemon juice, lemon zest, and minced garlic.",
			"Brush asparagus with half the olive oil mixture and season with salt.",
			"Brush salmon with remaining olive oil mixture.",
			"Place salmon skin-side down on grill and asparagus alongside.",
			"Grill salmon for 4-5 minutes per side, or until internal temperature reaches 145°F.",
			"Grill asparagus for 6-8 minutes, turning occasionally until tender-crisp.",
			"Serve immediately with lemon wedges.",
		],
		tags: ["healthy", "omega-3", "grilled", "low-carb", "high-protein"],
		createdAt: new Date("2024-01-15"),
		updatedAt: new Date("2024-01-15"),
	},
	{
		id: "2",
		name: "Lemon Herb Chicken Salad",
		description:
			"A light and refreshing chicken salad with fresh herbs and a tangy lemon dressing.",
		image: "https://picsum.photos/400/300?random=2",
		category: "Lunch",
		cuisine: "Mediterranean",
		prepTime: 15,
		cookTime: 0,
		servings: 2,
		difficulty: "Easy",
		calories: 320,
		nutrition: {
			protein: 28,
			carbs: 12,
			fat: 18,
			fiber: 3,
			sugar: 4,
		},
		ingredients: [
			{
				id: "1",
				name: "Grilled chicken breast",
				amount: 8,
				unit: "oz",
				notes: "cooked and diced",
			},
			{ id: "2", name: "Mixed greens", amount: 4, unit: "cups" },
			{
				id: "3",
				name: "Cherry tomatoes",
				amount: 1,
				unit: "cup",
				notes: "halved",
			},
			{ id: "4", name: "Cucumber", amount: 1, unit: "medium", notes: "sliced" },
			{
				id: "5",
				name: "Red onion",
				amount: 0.25,
				unit: "cup",
				notes: "thinly sliced",
			},
			{
				id: "6",
				name: "Fresh parsley",
				amount: 0.25,
				unit: "cup",
				notes: "chopped",
			},
			{
				id: "7",
				name: "Fresh mint",
				amount: 2,
				unit: "tbsp",
				notes: "chopped",
			},
			{ id: "8", name: "Lemon juice", amount: 2, unit: "tbsp" },
			{ id: "9", name: "Olive oil", amount: 2, unit: "tbsp" },
			{ id: "10", name: "Dijon mustard", amount: 1, unit: "tsp" },
			{ id: "11", name: "Salt", amount: 0.5, unit: "tsp" },
			{ id: "12", name: "Black pepper", amount: 0.25, unit: "tsp" },
		],
		instructions: [
			"In a large bowl, whisk together lemon juice, olive oil, Dijon mustard, salt, and pepper.",
			"Add diced chicken, cherry tomatoes, cucumber, red onion, parsley, and mint to the bowl.",
			"Toss everything together until well coated with the dressing.",
			"Divide mixed greens onto two plates.",
			"Top each plate with the chicken salad mixture.",
			"Serve immediately.",
		],
		tags: ["healthy", "salad", "chicken", "fresh", "light"],
		createdAt: new Date("2024-01-16"),
		updatedAt: new Date("2024-01-16"),
	},
	{
		id: "3",
		name: "Mediterranean Quinoa Bowl",
		description:
			"A nutritious and colorful quinoa bowl with Mediterranean flavors and fresh vegetables.",
		image: "https://picsum.photos/400/300?random=3",
		category: "Lunch",
		cuisine: "Mediterranean",
		prepTime: 15,
		cookTime: 15,
		servings: 2,
		difficulty: "Easy",
		calories: 380,
		nutrition: {
			protein: 12,
			carbs: 45,
			fat: 16,
			fiber: 6,
			sugar: 8,
		},
		ingredients: [
			{ id: "1", name: "Quinoa", amount: 0.75, unit: "cup", notes: "rinsed" },
			{ id: "2", name: "Water", amount: 1.5, unit: "cups" },
			{
				id: "3",
				name: "Cherry tomatoes",
				amount: 1,
				unit: "cup",
				notes: "halved",
			},
			{ id: "4", name: "Cucumber", amount: 1, unit: "medium", notes: "diced" },
			{ id: "5", name: "Red onion", amount: 0.25, unit: "cup", notes: "diced" },
			{
				id: "6",
				name: "Kalamata olives",
				amount: 0.25,
				unit: "cup",
				notes: "pitted and halved",
			},
			{
				id: "7",
				name: "Feta cheese",
				amount: 0.25,
				unit: "cup",
				notes: "crumbled",
			},
			{
				id: "8",
				name: "Fresh parsley",
				amount: 0.25,
				unit: "cup",
				notes: "chopped",
			},
			{ id: "9", name: "Lemon juice", amount: 2, unit: "tbsp" },
			{ id: "10", name: "Olive oil", amount: 2, unit: "tbsp" },
			{ id: "11", name: "Dried oregano", amount: 0.5, unit: "tsp" },
			{ id: "12", name: "Salt", amount: 0.5, unit: "tsp" },
			{ id: "13", name: "Black pepper", amount: 0.25, unit: "tsp" },
		],
		instructions: [
			"Rinse quinoa under cold water until water runs clear.",
			"In a medium saucepan, bring water to a boil. Add quinoa, reduce heat to low, cover, and simmer for 15 minutes.",
			"Remove from heat and let stand, covered, for 5 minutes. Fluff with a fork.",
			"In a large bowl, whisk together lemon juice, olive oil, oregano, salt, and pepper.",
			"Add cooked quinoa, cherry tomatoes, cucumber, red onion, olives, and parsley to the bowl.",
			"Toss everything together until well coated.",
			"Divide into two bowls and top each with crumbled feta cheese.",
			"Serve warm or at room temperature.",
		],
		tags: ["healthy", "vegetarian", "quinoa", "mediterranean", "bowl"],
		createdAt: new Date("2024-01-17"),
		updatedAt: new Date("2024-01-17"),
	},
	{
		id: "4",
		name: "Veggie Stir Fry with Tofu",
		description:
			"A quick and healthy stir fry loaded with colorful vegetables and protein-rich tofu.",
		image: "https://picsum.photos/400/300?random=4",
		category: "Dinner",
		cuisine: "Asian",
		prepTime: 15,
		cookTime: 10,
		servings: 2,
		difficulty: "Easy",
		calories: 280,
		nutrition: {
			protein: 18,
			carbs: 25,
			fat: 14,
			fiber: 6,
			sugar: 12,
		},
		ingredients: [
			{
				id: "1",
				name: "Firm tofu",
				amount: 8,
				unit: "oz",
				notes: "pressed and cubed",
			},
			{ id: "2", name: "Broccoli florets", amount: 2, unit: "cups" },
			{
				id: "3",
				name: "Bell pepper",
				amount: 1,
				unit: "medium",
				notes: "sliced",
			},
			{
				id: "4",
				name: "Carrot",
				amount: 1,
				unit: "medium",
				notes: "thinly sliced",
			},
			{ id: "5", name: "Snow peas", amount: 1, unit: "cup" },
			{ id: "6", name: "Garlic", amount: 3, unit: "cloves", notes: "minced" },
			{
				id: "7",
				name: "Fresh ginger",
				amount: 1,
				unit: "tbsp",
				notes: "grated",
			},
			{
				id: "8",
				name: "Soy sauce",
				amount: 2,
				unit: "tbsp",
				notes: "low-sodium",
			},
			{ id: "9", name: "Sesame oil", amount: 1, unit: "tbsp" },
			{ id: "10", name: "Cornstarch", amount: 1, unit: "tsp" },
			{ id: "11", name: "Water", amount: 2, unit: "tbsp" },
			{
				id: "12",
				name: "Green onions",
				amount: 2,
				unit: "stalks",
				notes: "sliced",
			},
		],
		instructions: [
			"Press tofu to remove excess water, then cut into 1-inch cubes.",
			"In a small bowl, mix cornstarch with water to make a slurry.",
			"Heat 1 tsp sesame oil in a large wok or skillet over medium-high heat.",
			"Add tofu cubes and stir-fry for 5-7 minutes until golden. Remove and set aside.",
			"Add remaining sesame oil to the wok. Add garlic and ginger, stir-fry for 30 seconds.",
			"Add broccoli, bell pepper, carrot, and snow peas. Stir-fry for 4-5 minutes until vegetables are tender-crisp.",
			"Return tofu to the wok. Add soy sauce and cornstarch slurry.",
			"Stir-fry for 1-2 minutes until sauce thickens.",
			"Garnish with green onions and serve over rice or noodles.",
		],
		tags: ["healthy", "vegetarian", "vegan", "stir-fry", "tofu"],
		createdAt: new Date("2024-01-18"),
		updatedAt: new Date("2024-01-18"),
	},
	{
		id: "5",
		name: "Berry Protein Smoothie Bowl",
		description:
			"A thick and creamy smoothie bowl packed with protein and antioxidants.",
		image: "https://picsum.photos/400/300?random=5",
		category: "Breakfast",
		cuisine: "American",
		prepTime: 5,
		cookTime: 0,
		servings: 1,
		difficulty: "Easy",
		calories: 320,
		nutrition: {
			protein: 25,
			carbs: 35,
			fat: 8,
			fiber: 8,
			sugar: 20,
		},
		ingredients: [
			{ id: "1", name: "Frozen mixed berries", amount: 1, unit: "cup" },
			{ id: "2", name: "Banana", amount: 1, unit: "medium", notes: "frozen" },
			{
				id: "3",
				name: "Greek yogurt",
				amount: 0.5,
				unit: "cup",
				notes: "plain",
			},
			{
				id: "4",
				name: "Protein powder",
				amount: 1,
				unit: "scoop",
				notes: "vanilla or berry flavor",
			},
			{ id: "5", name: "Almond milk", amount: 0.25, unit: "cup" },
			{ id: "6", name: "Chia seeds", amount: 1, unit: "tbsp" },
			{ id: "7", name: "Almonds", amount: 1, unit: "tbsp", notes: "sliced" },
			{
				id: "8",
				name: "Fresh berries",
				amount: 0.25,
				unit: "cup",
				notes: "for topping",
			},
		],
		instructions: [
			"Add frozen berries, frozen banana, Greek yogurt, protein powder, and almond milk to a blender.",
			"Blend on high until smooth and thick, adding more almond milk if needed for blending.",
			"Pour into a bowl.",
			"Top with chia seeds, sliced almonds, and fresh berries.",
			"Serve immediately.",
		],
		tags: ["healthy", "breakfast", "smoothie", "protein", "berries"],
		createdAt: new Date("2024-01-19"),
		updatedAt: new Date("2024-01-19"),
	},
	{
		id: "6",
		name: "Turkey and Avocado Wrap",
		description:
			"A satisfying wrap with lean turkey, creamy avocado, and fresh vegetables.",
		image: "https://picsum.photos/400/300?random=6",
		category: "Lunch",
		cuisine: "American",
		prepTime: 10,
		cookTime: 0,
		servings: 1,
		difficulty: "Easy",
		calories: 380,
		nutrition: {
			protein: 28,
			carbs: 32,
			fat: 16,
			fiber: 8,
			sugar: 6,
		},
		ingredients: [
			{ id: "1", name: "Whole wheat tortilla", amount: 1, unit: "large" },
			{ id: "2", name: "Sliced turkey breast", amount: 4, unit: "oz" },
			{
				id: "3",
				name: "Avocado",
				amount: 0.5,
				unit: "medium",
				notes: "mashed",
			},
			{ id: "4", name: "Lettuce leaves", amount: 2, unit: "large" },
			{ id: "5", name: "Tomato", amount: 1, unit: "medium", notes: "sliced" },
			{
				id: "6",
				name: "Cucumber",
				amount: 0.5,
				unit: "medium",
				notes: "sliced",
			},
			{
				id: "7",
				name: "Red onion",
				amount: 0.25,
				unit: "cup",
				notes: "thinly sliced",
			},
			{
				id: "8",
				name: "Greek yogurt",
				amount: 1,
				unit: "tbsp",
				notes: "for spreading",
			},
			{ id: "9", name: "Dijon mustard", amount: 1, unit: "tsp" },
			{ id: "10", name: "Salt", amount: 0.25, unit: "tsp" },
			{ id: "11", name: "Black pepper", amount: 0.125, unit: "tsp" },
		],
		instructions: [
			"In a small bowl, mix mashed avocado with Greek yogurt, Dijon mustard, salt, and pepper.",
			"Spread the avocado mixture evenly over the tortilla.",
			"Layer lettuce leaves, sliced turkey, tomato, cucumber, and red onion on top.",
			"Roll up the tortilla tightly, starting from one end.",
			"Cut in half diagonally and serve immediately.",
		],
		tags: ["healthy", "lunch", "wrap", "turkey", "avocado"],
		createdAt: new Date("2024-01-20"),
		updatedAt: new Date("2024-01-20"),
	},
];
